#!/usr/bin/env bash
# Use 'ifconfig' to get a list of network interfaces and their IPv4 addresses
ifconfig | grep -o 'inet addr:[0-9.]*' | awk -F: '{print $2}'

# Include the localhost IP (127.0.0.1) by querying the hostname
echo "127.0.0.1"
